using Tontine.Entities.Models_v1_4_sans;
using Tontine.Entities.ModelsDto;

namespace Tontine.Entities.ModelsDto
{
    public static partial class MeetTypeRubriqueMapper
    {
        public static MeetTypeRubriqueDto AdaptToDto(this MeetTypeRubrique p1)
        {
            return p1 == null ? null : new MeetTypeRubriqueDto()
            {
                TyperubId = p1.TyperubId,
                CreateUid = p1.CreateUid,
                UpdateUid = p1.UpdateUid,
                Libelle = p1.Libelle,
                IsOutcome = p1.IsOutcome,
                Nbmandataire = p1.Nbmandataire,
                Montantroute = p1.Montantroute,
                MontantPerson = p1.MontantPerson,
                Montantpenalite = p1.Montantpenalite,
                Code = p1.Code,
                Candelete = p1.Candelete,
                Maxsignature = p1.Maxsignature,
                AutoGenerated = p1.AutoGenerated,
                Required = p1.Required,
                IsActive = p1.IsActive,
                Numordre = p1.Numordre
            };
        }
        public static MeetTypeRubriqueDto AdaptTo(this MeetTypeRubrique p2, MeetTypeRubriqueDto p3)
        {
            if (p2 == null)
            {
                return null;
            }
            MeetTypeRubriqueDto result = p3 ?? new MeetTypeRubriqueDto();
            
            result.TyperubId = p2.TyperubId;
            result.CreateUid = p2.CreateUid;
            result.UpdateUid = p2.UpdateUid;
            result.Libelle = p2.Libelle;
            result.IsOutcome = p2.IsOutcome;
            result.Nbmandataire = p2.Nbmandataire;
            result.Montantroute = p2.Montantroute;
            result.MontantPerson = p2.MontantPerson;
            result.Montantpenalite = p2.Montantpenalite;
            result.Code = p2.Code;
            result.Candelete = p2.Candelete;
            result.Maxsignature = p2.Maxsignature;
            result.AutoGenerated = p2.AutoGenerated;
            result.Required = p2.Required;
            result.IsActive = p2.IsActive;
            result.Numordre = p2.Numordre;
            return result;
            
        }
    }
}