using System;
using System.Collections.Generic;

namespace Sqlite.Entities.Models1;

public partial class MeetTypeRubrique
{
    public long TyperubId { get; set; }

    public long? CreateUid { get; set; }

    public long? UpdateUid { get; set; }

    public byte[] CreateAt { get; set; } = null!;

    public byte[] UpdateAt { get; set; } = null!;

    public byte[] Libelle { get; set; } = null!;

    public byte[] IsOutcome { get; set; } = null!;

    public long Nbmandataire { get; set; }

    public byte[] Montantroute { get; set; } = null!;

    public byte[] MontantPerson { get; set; } = null!;

    public byte[] Montantpenalite { get; set; } = null!;

    public string Code { get; set; } = null!;

    public byte[] Candelete { get; set; } = null!;

    public long Maxsignature { get; set; }

    public byte[] AutoGenerated { get; set; } = null!;

    public byte[] Required { get; set; } = null!;

    public byte[] IsActive { get; set; } = null!;

    public long Numordre { get; set; }

    public byte[] TopayEachPeriode { get; set; } = null!;

    public byte[] AllowCustomAmount { get; set; } = null!;

    public virtual ICollection<MeetConfigVisa> MeetConfigVisas { get; set; } = new List<MeetConfigVisa>();

    public virtual ICollection<MeetMaxAllowSignature> MeetMaxAllowSignatures { get; set; } = new List<MeetMaxAllowSignature>();

    public virtual ICollection<MeetRubrique> MeetRubriques { get; set; } = new List<MeetRubrique>();
}
