using System;
using System.Collections.Generic;

namespace Tontine.Entities.Models_v1_4_sans01;

/// <summary>
/// Represente un type d&apos;evenements par exemple Mariage, Deces, Naissance, Cotisation, Decaissement ponctuel, etc.
/// </summary>
public partial class MeetTypeRubrique
{
    /// <summary>
    /// Identifiant du type d&apos;evenement
    /// </summary>
    public int TyperubId { get; set; }

    /// <summary>
    /// create_uid
    /// </summary>
    public long? CreateUid { get; set; }

    /// <summary>
    /// update_uid
    /// </summary>
    public long? UpdateUid { get; set; }

    /// <summary>
    /// Create_at
    /// </summary>
    public DateTime CreateAt { get; set; }

    /// <summary>
    /// Update_at
    /// </summary>
    public DateTime UpdateAt { get; set; }

    /// <summary>
    /// Libelle du type d&apos;evenement
    /// </summary>
    public string Libelle { get; set; } = null!;

    /// <summary>
    /// Indique si le type represente une sortie de caisse
    /// </summary>
    public bool IsOutcome { get; set; }

    /// <summary>
    /// Nombre de membres representant l&apos;asociation a l&apos;evenement
    /// </summary>
    public int Nbmandataire { get; set; }

    /// <summary>
    /// Montant du deplacement d&apos;un membre mandate par l&apos;association
    /// </summary>
    public decimal Montantroute { get; set; }

    /// <summary>
    /// Montant total associe a l&apos;evenement
    /// </summary>
    public decimal MontantPerson { get; set; }

    /// <summary>
    /// Montant de la penalite applicable en cas d&apos;absence aa l&apos;evenement
    /// </summary>
    public decimal Montantpenalite { get; set; }

    /// <summary>
    /// Les valeurs autorisees sont : {PRET, FONDENTRAIDE, COLLATION, EPARGNE, COTISATION, AIDE-NAISSANCE, AIDE-DECES, AIDE-MARIAGE, AIDE-DECES-CONJOINT, AIDE-DECES-FRERE, SECOURS, PENALITE-AIDES-DECES, PROJET}
    /// </summary>
    public string Code { get; set; } = null!;

    /// <summary>
    /// Indique si l&apos;utlisateur peut supprimer cette information
    /// </summary>
    public bool Candelete { get; set; }

    /// <summary>
    /// Nombre de signatures autorises pour signer un documents associe a ce type devenement
    /// </summary>
    public int Maxsignature { get; set; }

    /// <summary>
    /// Indique si le systeme cree automatiquement une rubrique correspondante quand sa valeur est TRUE
    /// </summary>
    public bool AutoGenerated { get; set; }

    /// <summary>
    /// Indique que toutes les rubriques de ce type sont automatiquement cotisees par les membres d&apos;une reunion
    /// </summary>
    public bool Required { get; set; }

    /// <summary>
    /// Lorsque sa valeur est a TRUE, le systeme peut proposser a l&apos;utilisateur (ou automatiquement) la creation des rubrique associee a ce type.
    /// </summary>
    public bool IsActive { get; set; }

    /// <summary>
    /// Defini l&apos;ordre dans lequel les rubriques de ce type peuevnt beneficier d&apos;une repartition automatique du montant verse par un membre d&apos;une reunion
    /// </summary>
    public int Numordre { get; set; }

    public virtual ICollection<MeetConfigVisa> MeetConfigVisas { get; set; } = new List<MeetConfigVisa>();

    public virtual ICollection<MeetMaxAllowSignature> MeetMaxAllowSignatures { get; set; } = new List<MeetMaxAllowSignature>();

    public virtual ICollection<MeetRubrique> MeetRubriques { get; set; } = new List<MeetRubrique>();
}
